//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTec.Aplicacao.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NTec.Aplicacao.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro desconhecido no processo de atualizar {0}..
        /// </summary>
        internal static string AtualizacaoErro {
            get {
                return ResourceManager.GetString("AtualizacaoErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atualização do {0} com sucesso..
        /// </summary>
        internal static string AtualizacaoSucesso {
            get {
                return ResourceManager.GetString("AtualizacaoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro. Cpf do {0}: {1} já cadastrado no sistema..
        /// </summary>
        internal static string CadastroDuplicado {
            get {
                return ResourceManager.GetString("CadastroDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro desconhecido no processo de cadastrar {0}..
        /// </summary>
        internal static string CadastroErro {
            get {
                return ResourceManager.GetString("CadastroErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrado {0} com sucesso..
        /// </summary>
        internal static string CadastroSucesso {
            get {
                return ResourceManager.GetString("CadastroSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo informado, não encontrado pelo sistema..
        /// </summary>
        internal static string CargoNaoEncontrado {
            get {
                return ResourceManager.GetString("CargoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro. Não encontrado no sistema o colaborador com maior hierarquia.
        /// </summary>
        internal static string ColaboradorHierarquiaErro {
            get {
                return ResourceManager.GetString("ColaboradorHierarquiaErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Colaborador informado, não encontrado pelo sistema..
        /// </summary>
        internal static string ColaboradorNaoEncontrado {
            get {
                return ResourceManager.GetString("ColaboradorNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro desconhecido no processo de deletar {0}..
        /// </summary>
        internal static string ExclusaoErro {
            get {
                return ResourceManager.GetString("ExclusaoErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exclusão do {0} com sucesso..
        /// </summary>
        internal static string ExclusaoSucesso {
            get {
                return ResourceManager.GetString("ExclusaoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Id não informado, id é obrigatório..
        /// </summary>
        internal static string IdObrigatorio {
            get {
                return ResourceManager.GetString("IdObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum registro encontrado..
        /// </summary>
        internal static string NaoEncontrado {
            get {
                return ResourceManager.GetString("NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro. Proibido de excluir cargo com colaboradores ainda nesse cargo..
        /// </summary>
        internal static string RegraExclusaoCargo {
            get {
                return ResourceManager.GetString("RegraExclusaoCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro. Proibido de excluir colaborador com posição de chefia..
        /// </summary>
        internal static string RegraExclusaoColaborador {
            get {
                return ResourceManager.GetString("RegraExclusaoColaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro. Proibido de excluir setor com colaboradores ainda alocado nele..
        /// </summary>
        internal static string RegraExclusaoSetor {
            get {
                return ResourceManager.GetString("RegraExclusaoSetor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Setor informado, não encontrado pelo sistema..
        /// </summary>
        internal static string SetorNaoEncontrado {
            get {
                return ResourceManager.GetString("SetorNaoEncontrado", resourceCulture);
            }
        }
    }
}
